### PR TITLE
A bit of changes

### PR DESCRIPTION
**Pull request by enderschesi**

### CODE REVIEW

**Comment by enderschesi** [comment]
@Paddyk45 please test this, i don't have an api key and idk how to get one so you r gonna have to test it, but it should work.

**Comment by Paddyk45** [comment]
Any reeason to make ServerSeeker::new() a Result? Theres no way that returns an Error

**Comment by Paddyk45** [comment]
Thanks, will test tomorrow

**Comment by enderschesi** [comment]
ok i tested
it does not work

**Comment by Paddyk45** [comment]
> ok i tested
> it does not work

Wait you didn't test?

**Comment by enderschesi** [comment]
> 

i said i didn't because i didn't have an api key before

**Comment by Paddyk45** [comment]
I have added most of the stuff in your PR, thanks!

**Pull request closed without merging**
